using System;
using MarketData.ToolBox.Utility;

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MarketData.Test
{
    [TestClass]
    public class EmailTests
    {
        [TestMethod]
        public void WillSendEmail()
        {
            //string message = $@"{DateTime.Now.ToLongDateString()} There was a problem processing GoogleFinance. \n\n{"This is a test."}";
            string message = string.Format(@"JJ,\nI updated the Dropbox minute and daily data.  \nThe process completed at {0}\n Files were copied.\n\nNick\n\nThis message was auto generated by the MarketData program.  Do not reply to the sending address.", DateTime.Now.ToLongDateString());
            Notifications n = new Notifications();
            var ret = n.CustomEmail("jjdambrosio@gmail.com", "Dropbox files have been updated", message);
            Assert.IsTrue(ret);
        }
    }
}
